package pbo_convert_suhu;
import pbo_pilih_project_java.Pilih_Project_Java_GUI;

import javax.swing.JOptionPane;

public class Convert_Suhu extends javax.swing.JFrame {
    public Convert_Suhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Konvert = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Suhu1 = new javax.swing.JTextField();
        Suhu2 = new javax.swing.JTextField();
        Suhu3 = new javax.swing.JTextField();
        InputSuhu = new javax.swing.JTextField();
        Hasil_Konversi_2 = new javax.swing.JComboBox();
        Hasil_Konversi_1 = new javax.swing.JComboBox();
        Hasil_Konversi_3 = new javax.swing.JComboBox();
        PilihSuhu = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("   PROGRAM KONVERSI SUHU");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Pilih suhu yang akan di convert :");

        Konvert.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Konvert.setText("KONVERSI");
        Konvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KonvertActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Reset.setText("RESET");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Kembali.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("____________________________________________________________________________");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("HASIL KONVERSI :");

        Suhu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Suhu1ActionPerformed(evt);
            }
        });

        Suhu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Suhu2ActionPerformed(evt);
            }
        });

        Suhu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Suhu3ActionPerformed(evt);
            }
        });

        InputSuhu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        InputSuhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputSuhuActionPerformed(evt);
            }
        });

        Hasil_Konversi_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Hasil_Konversi_2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hasil Konversi", "Celsius", "Fahrenheit", "Kelvin", "Reamur" }));
        Hasil_Konversi_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hasil_Konversi_2ActionPerformed(evt);
            }
        });

        Hasil_Konversi_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Hasil_Konversi_1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hasil Konversi", "Celsius", "Fahrenheit", "Kelvin", "Reamur" }));
        Hasil_Konversi_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hasil_Konversi_1ActionPerformed(evt);
            }
        });

        Hasil_Konversi_3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Hasil_Konversi_3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hasil Konversi", "Celsius", "Fahrenheit", "Kelvin", "Reamur" }));
        Hasil_Konversi_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hasil_Konversi_3ActionPerformed(evt);
            }
        });

        PilihSuhu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PilihSuhu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Input Suhu :", "Celsius", "Fahrenheit", "Kelvin", "Reamur" }));
        PilihSuhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihSuhuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(331, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(148, 148, 148))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Hasil_Konversi_3, 0, 507, Short.MAX_VALUE)
                                    .addComponent(Hasil_Konversi_1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Hasil_Konversi_2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Suhu3)
                                    .addComponent(Suhu2)
                                    .addComponent(Suhu1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(154, 154, 154)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(PilihSuhu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InputSuhu))
                        .addGap(436, 436, 436))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Konvert, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(490, 490, 490))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PilihSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Konvert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Kembali)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Hasil_Konversi_1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Suhu1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Hasil_Konversi_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Suhu2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(Hasil_Konversi_3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Suhu3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PilihSuhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihSuhuActionPerformed
        // Terdapat pilihan suhu untuk di convert dalam bentuk Combo Box (Celsius, Fahrenheit, Kelvin, Reamur)
    }//GEN-LAST:event_PilihSuhuActionPerformed

    private void InputSuhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputSuhuActionPerformed
        // Input Suhu dalam bentuk derajat (Celsius, Fahrenheit, Kelvin, Reamur)
    }//GEN-LAST:event_InputSuhuActionPerformed

    private void KonvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KonvertActionPerformed
        // Tombol Konvert untuk konversi suhu dari ... ke ...
        try {
            // Mendapatkan nilai input suhu dan kelembapan
            String inputSuhuText = InputSuhu.getText().trim();

            // Validasi input agar tidak kosong
            if (inputSuhuText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Masukkan nilai suhu", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            double inputSuhu = Double.parseDouble(inputSuhuText);

            // Mendapatkan satuan suhu yang dipilih oleh pengguna
            String selectedUnit = PilihSuhu.getSelectedItem().toString();

            // Menentukan hasil konversi
            double result1 = 0.0;
            double result2 = 0.0;
            double result3 = 0.0;

            switch (selectedUnit) {
                case "Celsius":
                    result1 = (inputSuhu * 9 / 5) + 32;  // Celsius to Fahrenheit
                    result2 = inputSuhu + 273.15;          // Celsius to Kelvin
                    result3 = inputSuhu * 4 / 5;           // Celsius to Reamur
                    Hasil_Konversi_1.setSelectedIndex(2);
                    Hasil_Konversi_2.setSelectedIndex(3);
                    Hasil_Konversi_3.setSelectedIndex(4);
                    break;
                case "Fahrenheit":
                    result1 = (inputSuhu - 32) * 5 / 9;    // Fahrenheit to Celsius
                    result2 = (inputSuhu - 32) * 5 / 9 + 273.15;  // Fahrenheit to Kelvin
                    result3 = (inputSuhu - 32) * 4 / 9;    // Fahrenheit to Reamur
                    Hasil_Konversi_1.setSelectedIndex(1);
                    Hasil_Konversi_2.setSelectedIndex(3);
                    Hasil_Konversi_3.setSelectedIndex(4);
                    break;
                case "Kelvin":
                    result1 = inputSuhu - 273.15;          // Kelvin to Celsius
                    result2 = (inputSuhu - 273.15) * 9 / 5 + 32;  // Kelvin to Fahrenheit
                    result3 = (inputSuhu - 273.15) * 4 / 5;  // Kelvin to Reamur
                    Hasil_Konversi_1.setSelectedIndex(1);
                    Hasil_Konversi_2.setSelectedIndex(2);
                    Hasil_Konversi_3.setSelectedIndex(4);
                    break;
                case "Reamur":
                    result1 = inputSuhu * 5 / 4;           // Reamur to Celsius
                    result2 = inputSuhu * 9 / 4 + 32;      // Reamur to Fahrenheit
                    result3 = inputSuhu * 5 / 4 + 273.15;  // Reamur to Kelvin
                    Hasil_Konversi_1.setSelectedIndex(1);
                    Hasil_Konversi_2.setSelectedIndex(2);
                    Hasil_Konversi_3.setSelectedIndex(3);
                    break;
                default:
                    // Menampilkan pesan jika tidak ada satuan yang dipilih
                    JOptionPane.showMessageDialog(this, "Pilih satuan suhu terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    return;
            }

            // Menetapkan hasil konversi ke TextField
            Suhu1.setText(String.valueOf(result1));
            Suhu2.setText(String.valueOf(result2));
            Suhu3.setText(String.valueOf(result3));

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Masukkan nilai suhu", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_KonvertActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // Tombol untuk mereset / menghapus seluruh input maupun output
        InputSuhu.setText("");
        Suhu1.setText("");
        Suhu2.setText("");
        Suhu3.setText("");
        PilihSuhu.setSelectedIndex(0);
        Hasil_Konversi_1.setSelectedIndex(0);
        Hasil_Konversi_2.setSelectedIndex(0);
        Hasil_Konversi_3.setSelectedIndex(0);
    }//GEN-LAST:event_ResetActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // Tombol Logout untuk kembali ke halaman login.java
        Pilih_Project_Java_GUI pilih_project = new Pilih_Project_Java_GUI();
        pilih_project.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KembaliActionPerformed

    private void Suhu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Suhu1ActionPerformed
        // Hasil komversi dari ... ke ...
    }//GEN-LAST:event_Suhu1ActionPerformed

    private void Suhu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Suhu2ActionPerformed
        // Hasil komversi dari ... ke ...
    }//GEN-LAST:event_Suhu2ActionPerformed

    private void Suhu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Suhu3ActionPerformed
        // Hasil komversi dari ... ke ...
    }//GEN-LAST:event_Suhu3ActionPerformed

    private void Hasil_Konversi_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hasil_Konversi_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hasil_Konversi_1ActionPerformed

    private void Hasil_Konversi_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hasil_Konversi_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hasil_Konversi_2ActionPerformed

    private void Hasil_Konversi_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hasil_Konversi_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hasil_Konversi_3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convert_Suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convert_Suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convert_Suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convert_Suhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convert_Suhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Hasil_Konversi_1;
    private javax.swing.JComboBox Hasil_Konversi_2;
    private javax.swing.JComboBox Hasil_Konversi_3;
    private javax.swing.JTextField InputSuhu;
    private javax.swing.JButton Kembali;
    private javax.swing.JButton Konvert;
    private javax.swing.JComboBox PilihSuhu;
    private javax.swing.JButton Reset;
    private javax.swing.JTextField Suhu1;
    private javax.swing.JTextField Suhu2;
    private javax.swing.JTextField Suhu3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
